using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerator
{
    [Generator]
    public sealed class ApiEndpointGenerator : IIncrementalGenerator
    {
        private const string GenerateAttr = "Application.Attributes.GenerateApiEndpointAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var serviceInterfaces = context.CompilationProvider
                .Select(static (compilation, ct) => CollectServiceInterfaces(compilation, ct));

            context.RegisterSourceOutput(serviceInterfaces, static (ctx, interfaces) =>
            {
                if (interfaces.Count == 0) return;
                ctx.AddSource("GeneratedEndpoints.g.cs", SourceText.From(GenerateSource(interfaces), Encoding.UTF8));
            });
        }

        private static List<ServiceInterfaceInfo> CollectServiceInterfaces(Compilation compilation, CancellationToken ct)
        {
            var generateAttrType = compilation.GetTypeByMetadataName(GenerateAttr);
            if (generateAttrType is null) return new List<ServiceInterfaceInfo>();

            var result = new List<ServiceInterfaceInfo>();

            foreach (var reference in compilation.References)
            {
                ct.ThrowIfCancellationRequested();
                if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly)
                    VisitNamespace(assembly.GlobalNamespace, generateAttrType, result, ct);
            }

            return result;
        }

        private static void VisitNamespace(
            INamespaceSymbol ns,
            INamedTypeSymbol generateAttrType,
            List<ServiceInterfaceInfo> result,
            CancellationToken ct)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                ct.ThrowIfCancellationRequested();
                if (type.TypeKind != TypeKind.Interface) continue;

                var attr = type.GetAttributes()
                    .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, generateAttrType));
                if (attr is null) continue;

                var routePrefix = GetNamedArg(attr, "RoutePrefix") ?? "";
                var tag = GetNamedArg(attr, "Tag") ?? DeriveTag(type.Name);

                var methods = new List<EndpointMethodInfo>();
                foreach (var member in type.GetMembers().OfType<IMethodSymbol>())
                    methods.Add(GetMethodInfo(member));

                result.Add(new ServiceInterfaceInfo(type.Name, type.ContainingNamespace.ToDisplayString(), routePrefix, tag, methods));
            }

            foreach (var subNs in ns.GetNamespaceMembers())
                VisitNamespace(subNs, generateAttrType, result, ct);
        }

        private static EndpointMethodInfo GetMethodInfo(IMethodSymbol method)
        {
            var parameters = method.Parameters
                .Select(p => new ParamInfo(
                    p.Name,
                    p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "")))
                .ToList();

            return new EndpointMethodInfo(method.Name, method.Name, parameters);
        }

        private static string GenerateSource(List<ServiceInterfaceInfo> interfaces)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Microsoft.AspNetCore.Builder;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using Microsoft.AspNetCore.Routing;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc;");

            foreach (var iface in interfaces)
                sb.AppendLine($"using {iface.Namespace};");

            sb.AppendLine();
            sb.AppendLine("namespace Api.Generated");
            sb.AppendLine("{");

            sb.AppendLine("    public static class GeneratedEndpointExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IEndpointRouteBuilder MapGeneratedEndpoints(this IEndpointRouteBuilder app)");
            sb.AppendLine("        {");
            foreach (var iface in interfaces)
                sb.AppendLine($"            app.Map{iface.Name}Endpoints();");
            sb.AppendLine("            return app;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");

            foreach (var iface in interfaces)
            {
                sb.AppendLine();
                sb.AppendLine($"    internal static class {iface.Name}EndpointExtensions");
                sb.AppendLine("    {");
                sb.AppendLine($"        public static IEndpointRouteBuilder Map{iface.Name}Endpoints(this IEndpointRouteBuilder app)");
                sb.AppendLine("        {");
                sb.AppendLine($"            var group = app.MapGroup(\"{iface.RoutePrefix}\").WithTags(\"{iface.Tag}\");");

                foreach (var method in iface.Methods)
                {
                    var lambdaParams = BuildLambdaParams(method, iface.Name);
                    var callArgs = string.Join(", ", method.Parameters.Select(p => p.Name));
                    sb.AppendLine($"            group.MapPost(\"{method.Route}\", async ({lambdaParams}) =>");
                    sb.AppendLine($"                Results.Ok(await service.{method.Name}({callArgs})));");
                }

                sb.AppendLine("            return app;");
                sb.AppendLine("        }");
                sb.AppendLine("    }");
            }

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildLambdaParams(EndpointMethodInfo method, string interfaceName)
        {
            var parts = new List<string>();

            foreach (var param in method.Parameters)
            {
                bool inRoute = method.Route.Contains("{" + param.Name + "}");
                parts.Add(inRoute
                    ? $"{param.TypeName} {param.Name}"
                    : $"[FromBody] {param.TypeName} {param.Name}");
            }

            parts.Add($"{interfaceName} service");
            return string.Join(", ", parts);
        }

        private static string? GetNamedArg(AttributeData attr, string name)
        {
            foreach (var kv in attr.NamedArguments)
                if (kv.Key == name) return kv.Value.Value as string;
            return null;
        }

        private static string DeriveTag(string interfaceName)
        {
            var name = interfaceName.TrimStart('I');
            return name.EndsWith("Service") ? name.Substring(0, name.Length - 7) : name;
        }
    }

    internal sealed class ServiceInterfaceInfo
    {
        public string Name { get; }
        public string Namespace { get; }
        public string RoutePrefix { get; }
        public string Tag { get; }
        public List<EndpointMethodInfo> Methods { get; }

        public ServiceInterfaceInfo(string name, string ns, string routePrefix, string tag, List<EndpointMethodInfo> methods)
        {
            Name = name; Namespace = ns; RoutePrefix = routePrefix; Tag = tag; Methods = methods;
        }
    }

    internal sealed class EndpointMethodInfo
    {
        public string Name { get; }
        public string Route { get; }
        public List<ParamInfo> Parameters { get; }

        public EndpointMethodInfo(string name, string route, List<ParamInfo> parameters)
        {
            Name = name; Route = route; Parameters = parameters;
        }
    }

    internal sealed class ParamInfo
    {
        public string Name { get; }
        public string TypeName { get; }

        public ParamInfo(string name, string typeName) { Name = name; TypeName = typeName; }
    }
}
